/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  public String getGreeting() {
    return "Hello World";
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    ConsoleUI ui = new ConsoleUI();
    ui.start();
  }
}
